<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ShipmentPlatform.Domain\ShipmentPlatform.Domain.csproj" />
    <ProjectReference Include="..\..\src\ShipmentPlatform.Application\ShipmentPlatform.Application.csproj" />
    <ProjectReference Include="..\..\src\ShipmentPlatform.Infrastructure\ShipmentPlatform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
